package com.dynamodemo.model;

import java.util.Date;

import org.springframework.data.annotation.Id;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBMarshalling;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBRangeKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;
import com.dynamodemo.config.FindMyPetMarshaller;
import com.fasterxml.jackson.annotation.JsonFormat;

@DynamoDBTable(tableName="FindMyPet")
public class PetTracker {
	
	private Cordinates coordinates;
	
	@Id
	@DynamoDBMarshalling(marshallerClass = FindMyPetMarshaller.class)
	private FindMyPetId id;
	
	private String petId;
	
	private String majorId;
	
	private String minorId;
	@JsonFormat(shape=JsonFormat.Shape.STRING, pattern="yyyy/MM/dd HH:mm:ss",timezone="America/New_York")
	private Date dateReported;
	
	@DynamoDBRangeKey
	public Date getDateReported() {
		return dateReported;
	}

	public void setDateReported(Date dateReported) {
		this.dateReported = dateReported;
	}

	private String reportedUserId;

	@DynamoDBHashKey
	public String getPetId() {
		return petId;
	}

	public void setPetId(String petId) {
		this.petId = petId;
	}
	
	public Cordinates getCoordinates() {
		return coordinates;
	}
	
	@Id
	@DynamoDBMarshalling(marshallerClass = FindMyPetMarshaller.class)
	public FindMyPetId getId() {
		return id;
	}

	@DynamoDBAttribute
	public String getMajorId() {
		return majorId;
	}

	public void setMajorId(String majorId) {
		this.majorId = majorId;
	}

	@DynamoDBAttribute
	public String getMinorId() {
		return minorId;
	}

	public void setMinorId(String minorId) {
		this.minorId = minorId;
	}

	@DynamoDBAttribute
	public String getReportedUserId() {
		return reportedUserId;
	}

	public void setReportedUserId(String reportedUserId) {
		this.reportedUserId = reportedUserId;
	}

	public void setCoordinates(Cordinates coordinates) {
		this.coordinates = coordinates;
	}

	public void setId(FindMyPetId id) {
		this.id = id;
	}

}
