package com.dynamodemo.model;

import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAttribute;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBAutoGeneratedKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBHashKey;
import com.amazonaws.services.dynamodbv2.datamodeling.DynamoDBTable;

@DynamoDBTable(tableName="Restaurant")
public class Restaurant {
	
	private String contact;
	
	private Cordinates coordinates;
	
	private String id;
	
	private Location location;
	
	private String name;
	
	private Pet pet;

	public Pet getPet() {
		return pet;
	}

	public void setPet(Pet pet) {
		this.pet = pet;
	}

	@Override
	public boolean equals(Object obj) {
		if (this == obj)
			return true;
		if (obj == null)
			return false;
		if (getClass() != obj.getClass())
			return false;
		Restaurant other = (Restaurant) obj;
		if (contact == null) {
			if (other.contact != null)
				return false;
		} else if (!contact.equals(other.contact))
			return false;
		if (id == null) {
			if (other.id != null)
				return false;
		} else if (!id.equals(other.id))
			return false;
		if (name == null) {
			if (other.name != null)
				return false;
		} else if (!name.equals(other.name))
			return false;
		return true;
	}

	@DynamoDBAttribute
	public String getContact() {
		return contact;
	}

	public Cordinates getCoordinates() {
		return coordinates;
	}

	@DynamoDBHashKey
	@DynamoDBAutoGeneratedKey 
	public String getId() {
		return id;
	}

	public Location getLocation() {
		return location;
	}

	@DynamoDBAttribute
	public String getName() {
		return name;
	}
	@Override
	public int hashCode() {
		final int prime = 31;
		int result = 1;
		result = prime * result + ((contact == null) ? 0 : contact.hashCode());
		result = prime * result + ((id == null) ? 0 : id.hashCode());
		result = prime * result + ((name == null) ? 0 : name.hashCode());
		return result;
	}

	public void setContact(String contact) {
		this.contact = contact;
	}
	public void setCoordinates(Cordinates coordinates) {
		this.coordinates = coordinates;
	}

	public void setId(String id) {
		this.id = id;
	}
	public void setLocation(Location location) {
		this.location = location;
	}

	public void setName(String name) {
		this.name = name;
	}
}
